### ISSUE TITLE
Erro para Carregar opções de entrega (apenas em cadastros novos)

### ISSUE THREAD

**Issue by phdiegues** [elisei/moip-transparente-magento#100]
Boa tarde amigos, como vão? Espero que estejam bem.

Seguinte, meu checkout está apresentando o seguinte erro:

depois de adicionar um produto ao carrinho, vou em FECHAR PEDIDO, depois coloco 1 email e faço o cadastro, depois vá para o checkout, as formas de entrega não aparecerão (vide imagem em anexo)

após esse erro, se você sair e logar novamente na conta cadastrada, aí as formas de entrega carregam normalmente, só nao carrega fazendo o cadastro na primeira vez

![222](https://user-images.githubusercontent.com/6341299/79793880-b1e8ab00-8327-11ea-944e-7a9699853247.jpg)

Alguém poderia, por favor me dar uma ajuda de como resolver isso?

Agradeço muito por qualquer ajuda.

Abração!

**Comment by Gambozo** [comment]
Boa tarde!
Tive um problema parecido.
O Bruno me ajudou na thread:
https://github.com/elisei/moip-transparente-magento/issues/98#issuecomment-600761636

**Comment by phdiegues** [comment]
@Gambozo, tudo bem?
Parece que deu certo!
Muuuuito obrigado meeeesmo cara, Deus abençõe!
