### ISSUE TITLE
Formas de pagamento não aparecem

### ISSUE THREAD

**Issue by ueltonVeslei** [elisei/moip-transparente-magento#101]
Testado em 2 Iphone 8 e um motorola k10, com múltiplas contas de usuário.
Magento 1.9.4.4 com tema Porto.

No report do Magento aparece o seguinte:

a:5:{i:0;s:56:"A forma de pagamento selecionada não está disponível.";i:1;s:1427:"#0 /home/magento/public_html/app/code/core/Mage/Payment/Model/Info.php(82): Mage::throwException('A forma de paga...')
#1 /home/magento/public_html/app/code/core/Mage/Sales/Model/Quote/Payment.php(218): Mage_Payment_Model_Info->getMethodInstance()
#2 /home/magento/public_html/app/code/local/MOIP/Onestepcheckout/controllers/IndexController.php(566): Mage_Sales_Model_Quote_Payment->getMethodInstance()
#3 /home/magento/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): MOIP_Onestepcheckout_IndexController->savePaymentMethodAction()
#4 /home/magento/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('savePaymentMeth...')
#5 /home/magento/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#6 /home/magento/public_html/app/code/core/Mage/Core/Model/App.php(381): Mage_Core_Controller_Varien_Front->dispatch()
#7 /home/magento/public_html/app/Mage.php(686): Mage_Core_Model_App->run(Array)
#8 /home/magento/public_html/index.php(83): Mage::run('', 'store')
#9 {main}";s:3:"url";s:41:"/onestepcheckout/index/savePaymentMethod/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:7:"default";}

Alguma sugestão do que seja?

**Comment by elisei** [comment]
Olá @ueltonVeslei 

Por favor analise a aplicação de remoção de js para a porto:
https://github.com/elisei/moip-transparente-magento/wiki/3-Configurar-Checkout-Moip-Carrinho#21-de-aplica%C3%A7%C3%A3o-para-o-tema-porto
