### ISSUE TITLE
Não redireciona para à compra

### ISSUE THREAD

**Issue by marcosnolasco** [elisei/moip-transparente-magento#105]
Prezados, depois que o usuário vai finalizar o pedido e não tem cadastro, ele então faz o cadastro e ao finalizar o cadastro não é redirecionado para a tela de pagamento, mas para a página inicial, fazendo com que ele tenha que ir novamente no carrinho e finalizar o pedido. Uso o Checkout do módulo de vocês.

**Comment by elisei** [comment]
@marcosnolasco 

Nesse processo de ser redirecionado para a home, o cliente fica logado, também isso não ocorre?

**Comment by marcosnolasco** [comment]
Sim, o cliente fica logado.

**Comment by elisei** [comment]
@marcosnolasco 

Nesse caso recomendo que entre em contato com o atendimento da moip em magento@moip.com.br informando o a url da loja e conta moip para o suporte. Trataremos por lá!
