### ISSUE TITLE
Novas políticas do Google não aceitam obrigatoriedade dos campos CPF e CNPJ

### ISSUE THREAD

**Issue by LuizSantos1** [elisei/moip-transparente-magento#106]
Olá, @elisei , tudo bem?
Eu uso o plugin de vocês em nosso site Magento 1.9/OpenMage
No entanto, estou tendo problemas com o Google Merchant porque eles agora
não aceitam mais que os campos CPF/CNPJ, data de nascimento e se não me engano 
até telefone e celular como "obrigatórios". Eles devem ser OBRIGATORIAMENTE, opcionais. 

Eles podem ser opcionais, mas o cliente não pode ser obrigado a informar esses dados. 
Acabei de ter uma conversa com uma atendente do Google que simulou uma compra no meu site. 

Eu fui a System/Configuration/Customer/Settings/Opções de Nome e Endereço 
e deixei como opcional, limpei o cache e mesmo assim, este campo segue como 
obrigatório no link: [https://meudominio.com/checkout/onepage/cadastro/](url)

Poderia me informar como desabilitar essa obrigatoriedade? 

Ah sim, informe o problema para o pessoal da Wirecard caso eles não estejam cientes. 

Att
Luiz Santos

**Comment by elisei** [comment]
Olá @LuizSantos1 

A Moip não aceita receber pagamentos sem CPF/CNPJ e Telefone/Celular, alias desconheço empresas no Brasil que permita, até mesmo por conta da nossa legislação que exige emissão de nota fiscal onde se faz obrigatório o número do documento fiscal. Portanto se for o caso de haver essa restrição você não poderá usar o nosso método de pagamento e como definido na politica de uso do módulo não poderá usar o módulo de checkout.

**Comment by LuizSantos1** [comment]
@elisei tudo bem?
Tudo isso que você alegou, eu também comuniquei ao Google.
A atendende do Google Merchant disse que entende as minhas alegações, mas que pelas novas diretrizes da LGPD,
esses dados não podem ser obrigatórios na página de cadastro do cliente. 

O cliente pode até informar esses dados, mas essa coleta deve ser opcional, caso o cliente queira processar
o pagamento por cartão de crédito, aí sim, ele deve informar esses dados, mas no cadastro do site, essa informação
não pode ser obrigatória, tem que ser opcional. Eu coloquei em maiúsculas, apenas para chamar a atenção para
essa mudança.  

Rogo por favor, que nos forneça essa opção de deixar como opcional, este módulo é de longe o melhor do mercado,
eu não queria desinstalar só por causa de uma birra entre a Google Merchant e a Wirecard. 

Apenas informe onde pode ser modificado e eu assumo a responsabilidade por minha conta e risco. O máximo
que pode acontecer é o cliente não informar esses dados e a Wirecard não processar o pagamento. 

A atendente deixou claro que não tem qualquer problema pedir esses dados, eles só não podem ser campos obrigatórios. 

Peço sua compreensão.

Atenciosamente,
Luiz

**Comment by LuizSantos1** [comment]
@elisei  tudo bem?
Tudo isso que você alegou, eu também comuniquei ao Google.
A atendende do Google Merchant disse que entende as minhas alegações, mas que pelas novas diretrizes da LGPD,
esses dados não podem ser obrigatórios na página de cadastro do cliente. 

O cliente pode até informar esses dados, mas essa coleta deve ser opcional, caso o cliente queira processar
o pagamento por cartão de crédito, aí sim, ele deve informar esses dados, mas no cadastro do site, essa informação
não pode ser obrigatória, tem que ser opcional. Eu coloquei em maiúsculas, apenas para chamar a atenção para
essa mudança.  

Rogo por favor, que nos forneça essa opção de deixar como opcional, este módulo é de longe o melhor do mercado,
eu não queria desinstalar só por causa de uma birra entre a Google Merchant e a Wirecard. 

Apenas informe onde pode ser modificado e eu assumo a responsabilidade por minha conta e risco. O máximo
que pode acontecer é o cliente não informar esses dados e a Wirecard não processar o pagamento. 

A atendente deixou claro que não tem qualquer problema pedir esses dados, eles só não podem ser campos obrigatórios. 

Eu inclusive tomei uma suspensão no Google Merchant por causa disso, segue o link do screenshort https://photos.app.goo.gl/PrJ4AtFqF22UxdtY9

Peço sua compreensão.

Atenciosamente,
Luiz
