### ISSUE TITLE
Problema Grave Reportado pelo Google Merchant - Sem solução dada pelo dev

### ISSUE THREAD

**Issue by LuizSantos1** [elisei/moip-transparente-magento#107]
Olá,
Estou com um problema GRAVÍSSIMO na integração do módulo Checkout para Magento/OpenMage

O Google Merchant me deu um strike por deixar os campos CPF, CNPJ, Razão Social e Data de Nascimento obrigatórios. Eles informaram que esses campos devem ser opcionais. Entendo as alegações do desenvolvedor e da Wirecard, mas dizer que o módulo de pagamento não funciona sem 
esses campos obrigatórios, e obrigar o lojista à torná-los obrigatórios mesmo deixando-os como opcional, não me parece razoável.

Tentei arqumentar com o Google dizendo que vários dos clientes grandes deles, deixam esses campos como obrigatórios. Eles seguramente
não quiseram me dizer que eu não sou um grande. 

Mas enfim, o questionamento deles me parece razoável, pois esses campos podem ser solicitados no próprio site do 
processador de pagamento em caso de redirect ou no iFrame. Casos do PagSeguro, para dar um exemplo. Que aliás, adquiriu a Wirecard.
Mas isso é apenas uma sugestão. 

Eles me disseram que se tornar esses campos opcionais, revisarão o meu caso e irão retirar o strike, pois eles não consideram essa 
solicitação obrigatória razoável. Que elas podem ser solicitadas de forma obrigatória pelo prossessador de pagamento, mas só quando o pagamento estiver sendo realizado e não no cadastro do cliente como está configurado atualmente.

Já tentei desabilitar esse obrigatoriedade no backend, mas não consegui. Encaminhei o e-mail enviado pelo Google ao Elisei para que ele veja que isso foi sim reportado como um problema pelo Google e não um capricho ou picuinha minha...

Sendo assim, rogo encarecidamente que não feche essa issue sem resolução. Se não quiser solucionar o problema, tudo bem,
mas deixe a issue aberta, assim, caso outro usuário do Github tenha uma solução ou maneira de contornar esse problema,
que informe aqui. Entendo que se encerre uma issue quando o problema não é relacionado ao módulo, como ocorre em
temas personalizados ou conflitos com um outro plugin. Mas neste caso específico, o problema está no módulo, que impõe
uma restrição mesmo quando desabilitamos a obrigatoriedade no backend. 

Lembrem-se, Magento é um projeto OpenSource. Até entenderia essas restrições numa plataforma fechada que permita
esse tipo de restrição em sua licença. Não é o caso do Magento. Mantenhamos o espírito que tornou o Magento possível e tornou as plataformas de ecommerce mais acessíveis e populares. 

Att
Luiz Santos

**Comment by elisei** [comment]
@LuizSantos1  

Orientação já realizada no Issue #106.
