### ISSUE TITLE
Erro MOip Carrinho !

### ISSUE THREAD

**Issue by fabioev** [elisei/moip-transparente-magento#12]
Fatal error: Call to a member function toOptionArray() on boolean in /home/lotus186/public_html/www.websitesempresariais.com.br/magento1/app/code/local/Mage/Adminhtml/Block/System/Config/Form.php on line 463

**Comment by elisei** [comment]
@fabioev não é possível usar um segundo módulo de checkout em conjunto, remova outros módulo de OSC que tenha.
