### ISSUE TITLE
updatemailmsg retorna 0

### ISSUE THREAD

**Issue by lemooca** [elisei/moip-transparente-magento#14]
ao tentar logar na tela que verifica se o e-mail existe na loja (/onestepcheckout/index/updateemailmsg/)
retorna 0 e não acontece nada

**Comment by elisei** [comment]
@lemooca siga os passos da wike para validação de js e pre-requisitos.

**Comment by lemooca** [comment]
era conflito mesmo no bootstrap, valeu
