### ISSUE TITLE
Pedidos mais antigos não abrem no Admin

### ISSUE THREAD

**Issue by leandromendonca** [elisei/moip-transparente-magento#15]
Olá,

Notei que os pedidos mais antigos, anteriores à instalação do módulo, não abrem no Admin. A montagem da página é interrompida, aparecem os menus mas não as informações do pedido.

Consegui arrumar mexendo no arquivo /app/design/adminhtml/default/default/template/MOIP/onestepcheckout/sales/order/view/tab/info/Customermessages.phtml. Veja anexo.

Por via das dúvidas também arrumei a cópia no base/default.

A questão é que a tabela moip_onestepcheckout não contém os pedidos antigos.

Espero ter ajudado!

Abraços, Leandro.

[Customermessages.phtml.txt](https://github.com/elisei/moip-transparente-magento/files/1083305/Customermessages.phtml.txt)

**Comment by elisei** [comment]
@leandromendonca se desejar pode encaminhar via pull que mergo aqui no projeto e você vira um contribuidor! :)

**Comment by leandromendonca** [comment]
@elisei Obrigado pela dica. Enviei agora o pull, espero ter feito da forma correta.
Abraços.

**Comment by elisei** [comment]
Dei merge até! :) tks!

Grato pela atenção, qualquer dúvida por favor deixe-me saber.


*Bruno Elisei - CTO*
*O2ti Soluções Web Ltda*
 (34) 99109-9596
 www.o2ti.com | Skype: Brunoelisei

2017-06-20 10:30 GMT-03:00 Leandro Mendonça <notifications@github.com>:
