### ISSUE TITLE
Quantidade de Caracteres do Cartão

### ISSUE THREAD

**Issue by Gambozo** [elisei/moip-transparente-magento#17]
Olá!
Há um erro que na contagem de caracteres impede fechar a compra quando se corrige o número do cartão.
Ex.: Entro com o número 4747474747474747 (Visa) e decido usar meu cartão Dinners ou AmEx. Apago o número do cartão Visa e digito o número do Dinners. Porém, após digitar o número e iniciar  lembro que meu Dinners (3649 010246 2661) não há crédito. Decido usar o Visa novamente. Quando termino de digitar o número do Visa e mudo o campo, ele acusa que "Tamanho do texto não satisfaz o espaço de texto especificado.".  Depois que acusa o erro, mesmo o número estando certo, não avança.
Se eu trocar um Visa por um Mastercard, avança normalmente.

Se o primeiro cartão digitado for um com menor número de dígitos, o campo aceita a entrada de um novo cartão com maior número de dígitos, porém o contrário não ocorre.

Não há erros de JS no console do navegador.

Segue imagens para melhor visualização.
![image](https://user-images.githubusercontent.com/22913826/27338002-62f373de-55aa-11e7-89ba-a947de17a77d.png)
![image](https://user-images.githubusercontent.com/22913826/27338059-8741990a-55aa-11e7-8116-99a206a5ebd0.png)
![image](https://user-images.githubusercontent.com/22913826/27338198-f0b945ea-55aa-11e7-91dc-9bf4119c421d.png)

**Comment by elisei** [comment]
@Gambozo 

Basta remover a class validate-length da linha

https://github.com/elisei/moip-transparente-magento/blob/master/app/design/frontend/base/default/template/MOIP/transparente/form/cc.phtml#L72
