### ISSUE TITLE
Cancelamento automático de pedidos

### ISSUE THREAD

**Issue by DaviSiqueira** [elisei/moip-transparente-magento#19]
Bom dia Bruno,

O cancelamento de pedidos por boletos não pagos está funcional?
Por aqui não está funcionando.

Eu comentei o cron no config.xml como você me orientou, pois estava recebendo status aguardando pagamento mesmo depois do pagamento já ter sido compensado.

Isso tem alguma relação com o fato dos pedidos não estarem sendo cancelados?
Vi também que teve uma nova atualização do módulo, tem alguma referencia com o que mencionei?

**Comment by elisei** [comment]
Olá @DaviSiqueira conforme atendimento via email, estou encerrando esse issues para continuidade por lá.
