### ISSUE TITLE
Modal "Esqueceu sua senha?"

### ISSUE THREAD

**Issue by Gambozo** [elisei/moip-transparente-magento#20]
Boa noite,
Tenho seu módulo instalado em várias lojas, porém o tema utilizado veio com Bootstrap 3.1.1/JQuery 1.8.3, com 24 colunas. Atualizei o JQuery para versão 1.9.1 e ajustei os erros. Atualizar o Bootstrap para 3.3.7 deforma a loja toda. Se eu ligo o bootstrap.js do módulo, a aparência não se deforma, porém gera conflito ( modal de recuperação de senha abre e fecha, dados inválidos, métodos de pagamento não funcionam). Se desativo, o conflito desaparece, porém deforma todo o checkout.
Fui obrigado a retornar para o JQuery 1.8.3. 
Há algum modo de contornar a situação?

**Comment by elisei** [comment]
@Gambozo tudo bem?

Desculpe a demora, bom você pode editar livremente os js e css em cada página, a minha dica é remover o do seu thema e deixar o comportamento como o nosso, para isto pode seguir esse tutorial:
https://github.com/elisei/moip-transparente-magento/wiki/Tratando-erros-de-Js.

E remover os componentes que vem do seu thema deixa apenas os da base do magento + o do nosso módulo.
