### ISSUE TITLE
Uncaught TypeError: $(...).fancybox is not a function

### ISSUE THREAD

**Issue by blopa** [elisei/moip-transparente-magento#21]
Bom dia.

Estou tentando utilizar o checkout do Moip, porém ao digitar o endereço de email na primeira etapa, nada acontece. Se eu olho no console do Chrome, aparece esses erros:

> quickview.js:4 Uncaught TypeError: $(...).fancybox is not a function
>     at HTMLDocument.<anonymous> (quickview.js:4)
>     at fire (jquery.js:3119)
>     at Object.fireWith [as resolveWith] (jquery.js:3231)
>     at Function.ready (jquery.js:3443)
>     at HTMLDocument.completed (jquery.js:3474)
> (anonymous) @ quickview.js:4
> fire @ jquery.js:3119
> fireWith @ jquery.js:3231
> ready @ jquery.js:3443
> completed @ jquery.js:3474

Todos os jquery.js com erro são do MOIP. Saberia dizer o que está acontecendo?

Obrigado

**Comment by blopa** [comment]
Segue o print http://imgur.com/a/UFVVR

**Comment by elisei** [comment]
Olá @blopa acredito que esteja usando o tema porto certo?

Se for ele possui varias funções que são excecutadas sem analisar se a classe ou id ainda existem no html. Como a proposta do site é remover pontos de fuga como menu, footer... podem ocorrer os erros que descreve.

A solução é simples, precisa remover os js. 

Segue como realiza-lo:
https://github.com/elisei/moip-transparente-magento/wiki/Tratando-erros-de-Js.
