### ISSUE TITLE
Erro com conta verificada por e-mail

### ISSUE THREAD

**Issue by renatoaleksander** [elisei/moip-transparente-magento#23]
Utilizo em minha loja a verificação da conta por e-mail e após isso é liberado o acesso a loja.

Ao criar a conta desta forma aparece uma mensagem de erro
exception 'Mage_Core_Exception' with message 'Essa conta não está confirmada.' in /aplicativos_web/loja/perfumescontratipos/magento/app/Mage.php:580 Stack trace: #0 /aplicativos_web/loja/perfumescontratipos/magento/includes/src/Mage_Customer_Model_Customer.php(180): Mage::exception('Mage_Core', 'Essa conta n\xC3\xA3o...', 1) #1 /aplicativos_web/loja/perfumescontratipos/magento/includes/src/__default.php(41501): Mage_Customer_Model_Customer->authenticate('renatoaleksande...', 'd04m03re') #2 /aplicativos_web/loja/perfumescontratipos/magento/app/code/local/MOIP/Onestepcheckout/controllers/IndexController.php(645): Mage_Customer_Model_Session->login('renatoaleksande...', 'd04m03re') #3 /aplicativos_web/loja/perfumescontratipos/magento/includes/src/__default.php(14334): MOIP_Onestepcheckout_IndexController->CreataAccountInitAction() #4 /aplicativos_web/loja/perfumescontratipos/magento/includes/src/__default.php(18813): Mage_Core_Controller_Varien_Action->dispatch('CreataAccountIn...') #5 /aplicativos_web/loja/perfumescontratipos/magento/includes/src/__default.php(18343): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http)) #6 /aplicativos_web/loja/perfumescontratipos/magento/includes/src/__default.php(21279): Mage_Core_Controller_Varien_Front->dispatch() #7 /aplicativos_web/loja/perfumescontratipos/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array) #8 /aplicativos_web/loja/perfumescontratipos/magento/index.php(83): Mage::run('default', 'store') #9 {main

**Comment by elisei** [comment]
@renatoaleksander o módulo não é preparado para esse processo mesmo. caso queira pode usar apenas o método de pagamento com qualquer outro checkout tem esse suporte, segue o link do módulo de pagamento isolado do checkout:
github.com/elisei/moip-apenas-pagamento
