### ISSUE TITLE
Erro link para pagamento admin

### ISSUE THREAD

**Issue by midiasim** [elisei/moip-transparente-magento#25]
O link para efetuar pagamento quando o pedido é criado pelo admin vem vazio.
Acontece em todos os lugares que aparece o link, no e-mail de confirmação de pedido, painel do cliente na loja e no pedido dentro do admin.
Esse recurso realmente ainda não funciona?

**Comment by elisei** [comment]
olá @midiasim sim ele ainda está em beta... sugiro altenativas como:
https://www.youtube.com/watch?v=1Lep1ol4gVk&feature=youtu.be
