### ISSUE TITLE
Discrepâncias Loja e MOIP

### ISSUE THREAD

**Issue by Gambozo** [elisei/moip-transparente-magento#26]
Bom dia,
Uso o Magento 1.9.1 e uma loja tem apresentado discrepâncias entre os dados no MOIP e aqueles usados pelos clientes no checkout.
O módulo está atualizado com as alterações até 03/09.
Observe.
MOIP:
![image](https://user-images.githubusercontent.com/22913826/31179039-2fa9c6be-a8f1-11e7-9902-d40432d16f45.png)

Loja:
![image](https://user-images.githubusercontent.com/22913826/31179202-ac795e02-a8f1-11e7-90fc-35ae6ef0b712.png)
As compras com cartão de crédito estão sendo exibidas na loja, dentro do painel administrativo, com dados diferentes daqueles utilizados pelos clientes. O próprio número de transação, PAY-************ esta diferente, incluindo a quantidade de parcelas.

Os boletos, em alguns a linha digitável fica em branco, com vencimento para 01-01-1970 e o link para visualizar simplesmente aponta para o home da loja.
![image](https://user-images.githubusercontent.com/22913826/31179836-6550b744-a8f3-11e7-8271-c63b1ad71ab0.png)
![image](https://user-images.githubusercontent.com/22913826/31180014-da3f0920-a8f3-11e7-8250-184cc3f74ac0.png)

Tenho essa mesma versão em outra loja, semelhante, e o erro não ocorre.
O que pode estar acontecendo de errado?

**Comment by elisei** [comment]
@Gambozo por acaso você aproveitou o banco de dados de alguma outra loja?

**Comment by Gambozo** [comment]
Exatamente. Pela praticidade, sou orientado a reaproveitar sempre o BD da última loja criada.
Acabei de ver que a tabela moip_transparentev2 tem dados antigos.
Posso limpar a tabela com segurança?

**Comment by elisei** [comment]
;) sim senhor.. pode limpar!
