### ISSUE TITLE
Boleto não está incluindo valor do frete

### ISSUE THREAD

**Issue by DaviSiqueira** [elisei/moip-transparente-magento#27]
Bom dia!

O pagamento via boleto não está incluindo o valor do frete.

![captura de tela 2017-10-10 as 09 50 31](https://user-images.githubusercontent.com/4529729/31387372-925cbaf6-ada0-11e7-9c36-2b3d88b6d152.png)
![captura de tela 2017-10-10 as 09 50 38](https://user-images.githubusercontent.com/4529729/31387373-9280916a-ada0-11e7-8bff-8bdca2ddfdc0.png)

**Comment by elisei** [comment]
@DaviSiqueira encerrando pois o atendimento foi realizado via magento@moip.com.br
