### ISSUE TITLE
Feedback e melhorias

### ISSUE THREAD

**Issue by joazvsoares** [elisei/moip-transparente-magento#31]
Olá pessoal, parabéns pelo excelente trabalho.

1) Quando configuramos para utilizar o status intermediário "Pagamento Pendente", ao finalizar a compra por padrão não aparecem as informações do pedido/pagamento na página de obrigado/success, isso acontece porque esse status no magento é definido como "não visível no frontend", então pra quem quiser utilizar esse status tem que adicionar uma config.

```
        <sales>
            <order>
                <states>
                    <pending_payment translate="label">
                        <visible_on_front>1</visible_on_front>
                    </pending_payment>
                </states>
            </order>
        </sales>
```
2) Na forma de pagamento com débito em conta, apenas o banco Itaú está habilitado, o restante das opções estão comentadas, existe alguma razão para estar dessa forma?

3) Quando adicionamos um novo endereço de entrega no processo de checkout, acredito que este novo endereço deveria aparecer como uma nova opção no bloco do lado esquerdo com os endereços do cliente, dessa forma é possível alternar entre os endereços cadastrados.

4) Tradução do "Show password" na opção de exibir o campo senha.

**Comment by elisei** [comment]
Olá @joazvsoares obrigado pelo feedback vou pontuar os item que possou:

1 - O pending_payment é um status nativo do Magento e não acho adequado nosso método mudar um comportamento nativo da plataforma, criamos as opções de status intermediário com 3 opções new e onhold são opções também nativas que são visíveis ao consumidor.

2 - A API V2 do Moip não tem outros bancos é somente o Itaú mesmo.

3 - Esse é o mesmo comportamento do Magento quando adiciona um novo endereço ele só é salvo ao final da order.

4 - Aprovada a sugestão está presente em novas versões.
