### ISSUE TITLE
Erro ao salvar pedido pelo admin

### ISSUE THREAD

**Issue by rfbastos** [elisei/moip-transparente-magento#32]
PHP Fatal error:  Call to undefined method MOIP_Transparente_Model_Admin::getDados() in /home/XXXXX/public_html/app/code/local/MOIP/Transparente/Model/Standard.php on line 32

**Comment by elisei** [comment]
@rfbastos já há um issues sobre isto: [29](https://github.com/elisei/moip-transparente-magento/issues/29)
a recomendação por hora é usar a alternativa descrita no video:
https://www.youtube.com/watch?v=1Lep1ol4gVk
