### ISSUE TITLE
Status Não Atualiza no Magento

### ISSUE THREAD

**Issue by Hzc2500** [elisei/moip-transparente-magento#34]
Estou utilizando o magento versão 1.7.0.2 e está ocorrendo algumas vezes que um pedido por boleto é pago e aceito pelo moip, porém no magento continua como "Aguardando Confirmação Pagamento".

                                    Como esta no magento
![aguardandopgt](https://user-images.githubusercontent.com/31808581/34877210-4e00996e-f78c-11e7-8a77-85fdf986288c.png)

                                     Como esta no MOIP
![pgtomoip](https://user-images.githubusercontent.com/31808581/34877278-8b4418f0-f78c-11e7-8e16-21ce6e8b770d.png)

Analisei um pouco e pensei que poderia ser por causa da configuração do cron, pois vi que o boleto estava com a data de validade para o dia 04-01-2018

![vencboleto](https://user-images.githubusercontent.com/31808581/34877323-c224da76-f78c-11e7-9f59-67c9c86cb19b.png)

E o pedido foi pago no dia 04-01-2018, com isso o cron rodado pelo Moip para alterar o status, poderia ter interferido? Pois ele está para rodar as 2:30 da manhã, no caso foi após o pedido ter sido aceito. Então no proximo dia 05-01-2018 o Cron rodou, porém a data de validade do boleto já teria passado, causando a não alteração do pedido

![cronmoip](https://user-images.githubusercontent.com/31808581/34877404-0b046734-f78d-11e7-9f20-6601a2c5d473.png)

Habilitei os logs e rodei o cron, o único log que obtive foi 

2018-01-12T12:20:03+00:00 DEBUG (7): ------- Set no state -------
2018-01-12T12:20:03+00:00 DEBUG (7): -9 day
2018-01-12T12:20:03+00:00 DEBUG (7): 2018-01-03 00:00:00
2018-01-12T12:20:03+00:00 DEBUG (7): 2018-01-03 23:59:59

**Comment by elisei** [comment]
Oi @Hzc2500 

O módulo já foi atualizado no ambiente?

**Comment by Hzc2500** [comment]
@elisei Sim está com a ultima versão 0.2.3 (transparente)

**Comment by elisei** [comment]
@Hzc2500 eu não mudo muito as versões quando gero uma atualização apenas quando necessito alterar algo em banco de dados. por isto oriento a sobrescrever a pasta app/code/local/transparente pela do repositório. 

Em teoria esse problema foi solucionado nos commits de nov/dez.

**Comment by Hzc2500** [comment]
@elisei Certo, poderei atualizar apenas na segunda-feira (15/01/2018), irei continuar analisando após a atualização.

Muito obrigado pelo rápido feedback. :+1:

**Comment by elisei** [comment]
;) blz qualquer coisa estou por aqui!
