### ISSUE TITLE
Dúvida

### ISSUE THREAD

**Issue by henriquemnr** [elisei/moip-transparente-magento#35]
Funciona com multistore?

**Comment by elisei** [comment]
Olá @henriquemnr qual recurso busca?

**Comment by henriquemnr** [comment]
Gostaria de saber se o módulo é compatível com o sistema de Multilojas do magento

**Comment by elisei** [comment]
Olá @henriquemnr todo módulo é "compatível", mas preciso saber qual recurso que busca de compatibilidade, por exemplo:
é possível desataviar formas de pagamento para substores, no entanto não possível associar outro usuário como recebedor em uma multistore. Então qual é a compatibilidade que busca?
