### ISSUE TITLE
Vencimento: 01-01-1970 boleto

### ISSUE THREAD

**Issue by jessestain** [elisei/moip-transparente-magento#36]
quando finalizo a compra o boleto nao aparece as informações e o vencimento aparece Vencimento: 01-01-1970

**Comment by elisei** [comment]
Olá @jessestain para realizar transações é necessário diversos processo como a validação dos dados e autenticação oAuth, você pode visualizar o motivo da não geração do seu pagamento analisando os logs gerados pelo módulo. Em especial o log: MOIP_Order.log da pasta var/log/MOIP/
