### ISSUE TITLE
Problema ao criar usuário para realizara compra.

### ISSUE THREAD

**Issue by gappear** [elisei/moip-transparente-magento#37]
Estou recebendo erro quando vou criar um usuário no momento do checkout e com isso o usuário é criado normalmente no magento, porém sem a senha.

O usuário fica travado e não consigo prosseguir.

Segue o erro:

Mage_Core_Exception: Login ou senha inválido(s). in C:\xampp\htdocs\magento\app\Mage.php:580 Stack trace: #0 C:\xampp\htdocs\magento\app\code\core\Mage\Customer\Model\Customer.php(189): Mage::exception('Mage_Core', 'Login ou senha ...', 2) #1 C:\xampp\htdocs\magento\app\code\core\Mage\Customer\Model\Session.php(214): Mage_Customer_Model_Customer->authenticate('vitormateuslima...', '124578') #2 C:\xampp\htdocs\magento\app\code\local\MOIP\Onestepcheckout\controllers\IndexController.php(645): Mage_Customer_Model_Session->login('vitormateuslima...', '124578') #3 C:\xampp\htdocs\magento\app\code\core\Mage\Core\Controller\Varien\Action.php(418): MOIP_Onestepcheckout_IndexController->CreataAccountInitAction() #4 C:\xampp\htdocs\magento\app\code\core\Mage\Core\Controller\Varien\Router\Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('CreataAccountIn...') #5 C:\xampp\htdocs\magento\app\code\core\Mage\Core\Controller\Varien\Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http)) #6 C:\xampp\htdocs\magento\app\code\core\Mage\Core\Model\App.php(365): Mage_Core_Controller_Varien_Front->dispatch() #7 C:\xampp\htdocs\magento\app\Mage.php(683): Mage_Core_Model_App->run(Array) #8 C:\xampp\htdocs\magento\index.php(83): Mage::run('', 'store') #9 {main}

**Comment by elisei** [comment]
Olá @gappear 

Você está com um conflito de js que impede o script de funcionar corretamente.

Conflitos de js não tem como serem tratados globalmente, é sempre um processo local. Para maiores informações entre em contato com o nosso suporte: magento@moip.com.br

**Comment by gappear** [comment]
Elisei, beleza?

Amigo ainda estou com dúvida se usar o magento 1 ou 2, por alguns motivos muito claros.

O Primeiro é que não consegui ainda colocar no magenta 1 o cálculo de frete, não faz sentido deixar o cálculo de frete somente no checkout, você sabe dizer se o magenta 2 tem isso de forma mais fácil?
O segundo motivo é igual, mas no carrinho.




Atenciosamente,

 
Vitor Mateus Lima

Grown And Appear
Mobile: +55-19-98160-7591

vendas@gappear.com.br

**Comment by elisei** [comment]
Olá @gappear tudo bom?

Esse tipo de pergunta é mais interessante postar em comunidades sobre Magento, por exemplo no facebook:
https://www.facebook.com/groups/magento.developers.brasil/
