### ISSUE TITLE
Status alterando após confirmação

### ISSUE THREAD

**Issue by Hzc2500** [elisei/moip-transparente-magento#38]
Bom dia, estou com um problema recorrente em alguns pedidos de uma loja, notei que acontece com alguns pedidos do MOIP.

![moipboleto](https://user-images.githubusercontent.com/31808581/36733056-33555f82-1bae-11e8-85fc-955048970985.png)

Ao analisar vi que o pedido está criando 2 faturas e por isso é confirmado 2 vezes.

![faturas](https://user-images.githubusercontent.com/31808581/36733066-39554898-1bae-11e8-8253-1669a8071b09.png)

Acredito que isso esteja ocorrendo pela configuração de Status Intermediário, gostaria de saber se posso desabilitar esta função, pois não entendi direito como ela funciona, pois quando o pedido é gerado com o status "Aguardando Pagamento" ele já não estaria "segurado" no magento?

![statussecundario](https://user-images.githubusercontent.com/31808581/36733155-7719012e-1bae-11e8-9089-88da007c6a73.png)

**Comment by elisei** [comment]
@Hzc2500 Por favor, atualize as pasta app/code/local/Transparente com as versões atuais do repositório isto deverá resolver o problema, caso ainda encontre dificuldades entre em contato com atendimento em: magento@moip.com.br

**Comment by Hzc2500** [comment]
@elisei Estarei atualizando e entrarei em contato pelo email se for necessário.

Muito obrigado novamente pelo suporte
