### ISSUE TITLE
Pedidos do Boleto - sem código de barras

### ISSUE THREAD

**Issue by Hzc2500** [elisei/moip-transparente-magento#40]
Boa tarde, um de nossos clientes, está relatando que  alguns pedidos gerados, estão vindo sem o código de barras.

Não consegui pegar o exemplo do boleto do cliente e no admin não é possível imprimir o boleto.

Porém o mesmo está com a data de vencimento para 01-01-1970, verifiquei o log do pedido em var/log/MOIP/MOIP_Order.log e está retornando um erro 

 ------ Resposta da Order ------
 { "ERROR" : "Token or Key are invalids" }

O que poderia ser? sendo que não são todos os pedidos.

![boletos](https://user-images.githubusercontent.com/31808581/37221781-d35ff7a0-23a9-11e8-8f28-986408e9e889.png)

**Comment by elisei** [comment]
@Hzc2500 01-01-1970 é a data padrão do PHP, não é que o boleto foi gerado para essa data e sim que não há uma data de vencimento para ela.
É importante analisar o além da linha de onde vê o erro a linha do CurlInfo da Order em especial o http_code se ela não 200 o servidor não pode ser atingido.

**Comment by Hzc2500** [comment]
@elisei Realizei a configuração do moip no magento novamente, tentei versões antigas do módulo, mas ainda assim, as vezes entra alguns pedidos sem o código de barras e sem data.
Verifiquei que na "------ Resposta do Pagamento ------" esta me retornando { "ERROR" : "Token or Key are invalids" } e me retorna o erro no header "http_code":401.

Porém não são todos os pedidos, são apenas alguns, você tem alguma ideia do que pode estar ocorrendo?
