### ISSUE TITLE
Frete grátis indevido para CEP restrito

### ISSUE THREAD

**Issue by flaviomdutra** [elisei/moip-transparente-magento#42]
Elisei,

Tudo bem?

Criamos uma promoção no Magento aplicando o Frete Grátis para alguns estados, mas verificamos que quando o cliente cadastra um endereço de cliente diferente, ele não aplica o desconto.

Ele aplica o desconto apenas para o primeiro endereço cadastrado, não aplica desconto para o um outro endereço de envio, poderia me ajudar nessa questão.

Abraço

**Comment by elisei** [comment]
@flaviomdutra Você deverá mudar a lógica da promoção para faixa de CEP e não pelo estado, o processo de calculo de frete é disparado pela entrada do CEP informado, processo esse que vem antes de se obter o estado no formulário.

**Comment by flaviomdutra** [comment]
@elisei, muito obrigado, vou trabalhar dessa maneira!
