### ISSUE TITLE
MOIP Pagamento não está notificando usuário - Status Processing

### ISSUE THREAD

**Issue by flaviomdutra** [elisei/moip-transparente-magento#43]
@elisei, tudo bem?

Seria possível notificarmos o usuário, quando o Status muda para Processing?

Nesse Status que está pago pelo cartão certo?

Abraço

**Comment by elisei** [comment]
Oi @flaviomdutra a notificação de fatura é automática, o próprio magento a faça o email é o  new_invoice!

**Comment by flaviomdutra** [comment]
@elisei, olha por exemplo, quando ele faz a Captura ele não envia e-mail para o cliente notificando ele só avisa quando enviamos o pedido.

Estou anexando um exemplo.

<img width="686" alt="screen shot 2018-03-23 at 11 05 09" src="https://user-images.githubusercontent.com/7936766/37833518-36276f04-2e8a-11e8-89a9-11bd0287ab3c.png">

**Comment by elisei** [comment]
@flaviomdutra isto é uma definição do próprio magento ele não cria (nem permite) notificação de status para faturação de um pedido. Ele dispara e permite apenas envio ou não de comunicação de nova fatura. Contacte seu desenvolvedor Magento para maiores informações sobre esse fluxo.
