### ISSUE TITLE
Pedidos sem código de barras

### ISSUE THREAD

**Issue by Hzc2500** [elisei/moip-transparente-magento#44]
@elisei Desculpe abrir novamente um chamado igual ao do #40 porém realizei a configuração do moip no magento novamente, tentei versões antigas do módulo, mas ainda assim, as vezes entra alguns pedidos sem o código de barras e sem data.
Verifiquei que na "------ Resposta do Pagamento ------" esta me retornando { "ERROR" : "Token or Key are invalids" } e me retorna o erro no header "http_code":401.

Porém não são todos os pedidos, são apenas alguns, você tem alguma ideia do que pode estar ocorrendo?

**Comment by elisei** [comment]
@Hzc2500 tudo bem?

Você está trabalhando em ambient de teste (sandbox) ou em produção?

**Comment by elisei** [comment]
@Hzc2500 pode mandar o log completo das requisições que deram erro?

ATENÇÂO, o log dispoem de informações sensiveis como o token usado por isto faça o envio para a central de atendimento do moip em: magento@moip.com.br
