### ISSUE TITLE
Atualização TLS 1.2

### ISSUE THREAD

**Issue by lemooca** [elisei/moip-transparente-magento#45]
Boa tarde, conforme orientação da MOIP, gostaria de saber se haverá atualização no módulo

https://dev.moip.com.br/page/atualiza%C3%A7%C3%A3o-do-protocolo-de-seguran%C3%A7a-tls-12?utm_campaign=TLS&utm_source=hs_email&utm_medium=email&utm_content=61919104&_hsenc=p2ANqtz-8B9fAJZeYDVmHaBE25JqYd6mmNFJCqpEYwrwPv3p9pOQmy4ZAUdF_MCym6c0_DsWydYm13QmofO426VB0sOUtXtsB2pw&_hsmi=61919104

Agradeço a atenção.

**Comment by elisei** [comment]
@lemooca não há nenhuma informação sobre módulos, isto é uma configuração de infra... Por favor siga os passos indicados no guia.
