### ISSUE TITLE
Pedidos do Boleto - sem código de barras

### ISSUE THREAD

**Issue by higuoliveira98** [elisei/moip-transparente-magento#46]
Bom dia, primeiramente desculpa estar abrindo uma nova issue igual a #40 e #44, mas nosso cliente relatado nas issues citadas está novamente com esse problema.

O boleto para um determinado pedido está sem código de barras e a data de vencimento é 01/01/1970.
Ao analisar os logs do Moip verificamos o código de erro abaixo para o pedido em questão:
  "code": "ORD-010", "path": "items", "description": "É necessario informar pelo menos um item."

Porém no painel da loja do nosso cliente, consta um item no pedido. Você sabe me dizer o que pode ter acontecido para o moip não conseguir capturar o item do pedido ?

**Comment by higuoliveira98** [comment]
@elisei Não, na verdade o produto no momento está sem estoque, seu valor é de R$2580,00 com 10% de desconto no boleto. Porém, por estar sem estoque, não é possível finalizar a compra.

**Comment by higuoliveira98** [comment]
@elisei acho que não fui claro o suficiente.

Quando um produto está sem estoque, eu não consigo adicionar ao carrinho, nem finalizar a compra.
O valor do produto que foi comprado é de R$2580,00 com 10% de desconto no boleto.

Porém no registro desse pedido que deu problema no boleto, o mesmo produto aparece com valor zerado.

**Comment by elisei** [comment]
@higuoliveira98 okay, vamos fazer um teste então, altere o estoque dele e tente comprar novamente veja como se comportará!

**Comment by higuoliveira98** [comment]
@elisei Teste efetuado, o código de barras gerou normalmente. Segue log:

[logMoip.txt](https://github.com/elisei/moip-transparente-magento/files/1903775/logMoip.txt)

**Comment by elisei** [comment]
@higuoliveira98 okay, então acompanhe novas transações e se necessário por favor nos comunique! ;)
