### ISSUE TITLE
BUG Endereço "Rua"

### ISSUE THREAD

**Issue by brunotda** [elisei/moip-transparente-magento#48]
@elisei Encontrei um bug no campo RUA, quando autopreenchido pelo CEP ex: 06711-020, o nome da rua é muito longo, caso o usuário adicione "." para abreviar é confirmado na edição mas ao finalizar o pagamento no checkout aponta erro no campo "RUA" mas esta direcionando para outra página /checkout/onepage/undefined.

**Comment by brunotda** [comment]
Rua General Fernando Vascon. Cavalcanti de Albuquerque

**Comment by brunotda** [comment]
NÃO FUNCIONA: Rua General Fernando Vasconcellos Cavalcanti de Albuquerque
NÃO FUNCIONA: Rua General Fernando V Cavalcanti de Albuquerque
NÃO FUNCIONA: Rua General Fernando Vascon. Cavalcanti de Albuquerque

**Comment by elisei** [comment]
Olá @brunotda de fato o checkout irá impedir cadastros com o valor de street superior a 57 caracteres conforme pode verificar no print: http://nimb.ws/oijW9r não sendo possível ao cliente via nosso checkout realizar um cadastro sem antes editar esse item.

**Comment by brunotda** [comment]
@elisei , no casso ele de 57 caracteres ele apontou o erro mas quando remove alguns caracteres ele passa para o FINALIZAR COMPRA ao selecionar meio de pagamento, entrega e clicar em finalizar aparece um erro no modal rapidamente e já redireciona para a página "/checkout/onepage/undefined", realizei o teste no ambiente modelo e apresentou o mesmo bug. Faz um teste com este CEP e remove alguns caracteres para ficar abaixo dos 57.

**Comment by elisei** [comment]
Olá @brunotda 
Respeitado o limite de caracteres é possível realizar o pagamento sem nenhum problema conforme poderá verificar no print:
http://nimb.ws/jMwuAy
Além disso você poderá testar em nossa loja demo:
http://moip.loja.ninja/produto-teste se o problema for detectado também em nossa store modelo por favor reabra o isseus se for apenas local você terá que verificar suas personalizações, caso necessite de algum apoio adicional poderá ser solicitado em magento@moip.com.br

**Comment by brunotda** [comment]
Estes testes foram realizados no ambiente demo.

![moip2](https://user-images.githubusercontent.com/15007670/39194781-cf4a2d00-47b4-11e8-9364-efc037e08a3c.png)
![moip3](https://user-images.githubusercontent.com/15007670/39194783-cf7e28da-47b4-11e8-8a4d-f125d84ef7b8.png)
![moip_1](https://user-images.githubusercontent.com/15007670/39194786-d02b260c-47b4-11e8-8b5b-4935943415e2.png)

**Comment by elisei** [comment]
Oi @brunotda isto não está muito coerente, você pode me dizer como cadastrou tal endereço?

**Comment by brunotda** [comment]
@elisei o cadastro foi direto pelo painel da MOIP com os seguintes dados:
![cadastro-moip](https://user-images.githubusercontent.com/15007670/39195063-60bded58-47b5-11e8-8ff9-00775c278014.png)

**Comment by elisei** [comment]
Olá @brunotda então o módulo aqui presente é de checkout e não de cadastro essa é uma sessão nativa do magento e não do módulo.

**Comment by brunotda** [comment]
@elisei  mandei esta imagem para você ver o que foi cadastrado no endereço, mas ele foi cadastrado pelo módulo da MOIP.

**Comment by elisei** [comment]
@brunotda bom nesse caso preciso que faça um screenshot de como foi permitido em nosso checkout realizar esse cadastro, pois todos os teste realizados não demonstrou ser possível realizar tal cadastro em nosso fluxo de checkout.

**Comment by brunotda** [comment]
![cadastro_moip](https://user-images.githubusercontent.com/15007670/39196056-951d6efa-47b7-11e8-9819-af555fd69893.png)

**Comment by elisei** [comment]
Olá @brunotda isto só é possivel se você editar no html do form o valor. Infelizmente não é possível como descrevi antes reproduzir o seu erro, nesse caso oriento a verificar suas personalizações, caso necessite de algum apoio adicional poderá ser solicitado em magento@moip.com.br

**Comment by brunotda** [comment]
@elisei isto foi direto no ambiente DEMO, sem editar nada.

**Comment by brunotda** [comment]
@elisei este erro só consta no cadastro na 1° vez, verifiquei que no editar endereço ele bloqueia o cadastro da rua escrita da mesma forma.

**Comment by elisei** [comment]
Oi @brunotda então, por isto é muito importante que grave o fluxo completo desde a add do produto até a finalização, segue um plugin para chrome com essa finalidade: https://chrome.google.com/webstore/detail/screencastify-screen-vide/mmeijimgabbpbgpdklnllpncmdofkcpn

**Comment by brunotda** [comment]
https://drive.google.com/file/d/14rES-MpfE8Yd0_ToLwPTxV-dudaCFEbo/view

**Comment by elisei** [comment]
Olá @brunotda havia uma divergência do minimo de caracteres presentes na phtml do address shipping, correção realizada no arquivo https://github.com/elisei/moip-transparente-magento/blob/master/app/design/frontend/base/default/template/MOIP/onestepcheckout/checkout/daskboard/onepage/shipping/shipping_form.phtml#L79 por favor atualize a sua aplicação.
