### ISSUE TITLE
Widget de parcelamento

### ISSUE THREAD

**Issue by DaviSiqueira** [elisei/moip-transparente-magento#5]
O widget de parcelamento não atualiza os valores das parcelas ao escolher a opção de um produto configurável quando o mesmo acrescenta um valor ao produto.

**Comment by elisei** [comment]
Olá Davi

Não há suporte no magento para um

**Comment by elisei** [comment]
Olá Davi,

No magento não há função valida para todas as stores que pudessemos chamar para obter esse recurso o que torna inviavel o desenvolvimento dela, no entanto nosso código é aberto e as próprias funções que usamos o ajudara a desenvolver isto para o seu site.
