### ISSUE TITLE
retorno do checkout para carrinho

### ISSUE THREAD

**Issue by davirs** [elisei/moip-transparente-magento#52]
Olá. Quando o cliente não utiliza o checkout MOIP para fazer o cadastro e ou tem alguma inconsistência no cadastro, quando ele clica em finalizar pedido sai do checkout e vai para o carrinho.
Não exibe nenhum retorno de erro para saber exatamente o que é, simplesmente retorna para o carrinho.

Já identifiquei um caso que o CEP não estava cadastrado totalmente no site do correio e foi preenchido o endereço manualmente:

![cep](https://user-images.githubusercontent.com/4355062/40449806-0c49ce60-5eb0-11e8-80a8-a9ac578c19a0.png)

se alterar somente o endereço para algum existente integralmente nos correios o checkout finaliza sem problema algum.
como proceder?

**Comment by elisei** [comment]
@davirs a consulta de cep é feita em uma api de terceiros, não temos como manipular tais retornos.

**Comment by davirs** [comment]
@elisei Obrigado pelo retorno.
O problema não é a consulta mas sim o tratamento. Porque o checkout direciona para o carrinho sem nenhum tipo de tratamento? Este é o X da questão.
Você informa que não da para manipular, da ao menos para manter no checkout sem direcionamento?

CEP foi apenas um exemplo, qualquer outro tipo de erro vai acontecer mesma coisa, lembrando que muita gente não faz cadastro no checkout.
