### ISSUE TITLE
Não está funcionado a finalização com métodos de terceiros

### ISSUE THREAD

**Issue by mozgbrasil** [elisei/moip-transparente-magento#55]
Boa Tarde

Conforme imagens

Vemos que está sendo exibido o erro 302 na tentativa de acesso a pagina de sucesso

Esse erro está ocorrendo com métodos de terceiros

Vemos que nesse exemplo estou usando o módulo da PagSeguro

https://github.com/r-martins/PagSeguro-Magento-Transparente

![captura de tela de 2018-06-06 17-50-12](https://user-images.githubusercontent.com/17202780/41064526-2d12a8a8-69b2-11e8-967b-6c03d6209950.png)
![captura de tela de 2018-06-06 17-51-10](https://user-images.githubusercontent.com/17202780/41064546-390df338-69b2-11e8-9b20-34d9847e60e5.png)

**Comment by elisei** [comment]
@mozgbrasil não oferecemos qualquer suporte a módulos de terceiros, caso queira usar o moip associado a outro checkout utilize a versão:
http://github.com/elisei/moip-apenas-pagamento/
