### ISSUE TITLE
Parcelamento no Produto com Bootstrap 4.

### ISSUE THREAD

**Issue by Gambozo** [elisei/moip-transparente-magento#56]
Olá, Bruno!
Recentemente atualizamos uma loja para o tema Porto 3.1 - Magento 1.9.3.8 e tive algumas inconsistências no checkout, com campos desformatados, etc. Fui verificar e o tema usa Bootstrap 4.0.  Com poucos ajustes tudo ficou 100%, porém o parcelamento dentro dos produtos não era exibido de forma alguma.
Puxei os arquivos view.phtml e list.phtml de uma outra instalação que usa o Porto versão 2.7 esperando que o parcelamento fosse funcionar normalmente.
O widget para categorias, que também embuti nos filtros "mais vendidos/destacados/novos", funciona perfeitamente. Já aquele para o produto, estou tendo que usar o modo reduzido das categorias.
O widget para produtos `<?php echo $this->getChildHtml('parcelas') ?>` não gera erro de JS e simplesmente nem sinal.
Com o widget "integral", `<?php echo $moip->getParcelas($_product->getFinalPrice(), 'integral'); ?>`gera erro no arquivo view.phtml, exatamente onde o coloquei, e é exibida a palavra "Array" no produto, sem deixar de exibir o produto.
`44:37+00:00 ERR (3): Notice: Array to string conversion  in /home/public_html/app/design/frontend/smartwave/porto/template/catalog/product/view.phtml on line 244`
Não sei se fui claro, mas chuto que seja alguma incompatibilidade com o tema ou Bootstrap 4.
Poderia me orientar na resolução?

**Comment by elisei** [comment]
@Gambozo soltei uma correção agora o nome do método...
https://github.com/elisei/moip-transparente-magento/commit/1d7a571d9f7cdf077de525f5679339017e1cbb50

Por favor veja se a sua versão está atualizada.

**Comment by Gambozo** [comment]
@elisei Vou testar. Obrigado!

**Comment by Gambozo** [comment]
Perfeito. Funcionou.
Muito obrigado!
