### ISSUE TITLE
Estado não carrega na pagina de cadastro

### ISSUE THREAD

**Issue by luizgustavoagomes** [elisei/moip-transparente-magento#57]
Boa tarde estou com um problema que na pagina de registro depois que informa o cep ele não carrega o estado. Eu uso a versão 1.9.3.8 do magento.
![miop](https://user-images.githubusercontent.com/26871695/42186716-0e3cf7f4-7e24-11e8-8ebe-a426dcb4b716.PNG)

**Comment by elisei** [comment]
Olá @luizgustavoagomes para os estados brasileiros serem carregados é necessário que execute o sql de sua tradução aqui no link https://gist.github.com/elisei/1687f34483da88cd8b1d2a6fb20be2cc você encontra o sql da tradução oferecida pelo Mario San.

**Comment by luizgustavoagomes** [comment]
Muito Obrigado.
