### ISSUE TITLE
Não carrega as opções de entrega

### ISSUE THREAD

**Issue by luizgustavoagomes** [elisei/moip-transparente-magento#58]
Não apresenta as opções de entrega com os fretes, estou usando o modulo do correio do pedro teixeira.

![envio](https://user-images.githubusercontent.com/26871695/42545081-f9b52a0e-848b-11e8-8bd1-d13de974317e.PNG)

**Comment by elisei** [comment]
Olá @luizgustavoagomes 
O método de envio carrega na sessão checkout/cart/ ou também não retorna?

**Comment by luizgustavoagomes** [comment]
no checkout/cart/ ele carrega 
![teste](https://user-images.githubusercontent.com/26871695/42602793-7ee9d1f6-8541-11e8-977d-26add118fdd0.PNG)

**Comment by elisei** [comment]
@luizgustavoagomes acredito que tenha algum erro de js no console certo? caso tenha é preciso trata-los assim que feito o checkout já exibirá o meio de pagamento!

**Comment by luizgustavoagomes** [comment]
Ok obrigado vou dar uma olhada neles.

**Comment by elisei** [comment]
@luizgustavoagomes qq coisa em magento@moip.com.br você pode encaminhar os dados de acesso lá que fazemos essa ação para você!

**Comment by oavandre** [comment]
Ola, estou tendo mesmo problema posso enviar o email para magento@moip.com.br?

![image](https://user-images.githubusercontent.com/34844149/87105264-d9695880-c230-11ea-8b55-42671fb4d799.png)
