### ISSUE TITLE
Incorporar social login ao modulo

### ISSUE THREAD

**Issue by luizgustavoagomes** [elisei/moip-transparente-magento#59]
Teria alguma forma de incorporar um botão de social login ao modulo?

**Comment by elisei** [comment]
@luizgustavoagomes 
Tem várias mas ao meu ver depende de alteração que ainda são "consolidadas"... recomendo primeiro mover o cpf para um atributo de endereço, aí sua autenticação precisará só do nome e email, precisará habilitar vat_id no endereço, caso necessário algo do nosso lado para isto te envio.

**Comment by guittavares** [comment]
Boa tarde, tudo bem?
Gostaria de saber como posso realizar este procedimento, tendo em vista que o campo de CPF não é presente no código do arquivo de edição dos dados cadastrais e mesmo incluindo o input, apresenta CPF inválido.
