### ISSUE TITLE
updateordermethod net::ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by andersonkoester** [elisei/moip-transparente-magento#6]
Ao finalizar o checkout está disparando Timeout no método /onestepcheckout/index/updateordermethod/

O cenário para replicar o erro:
Windows 7
Chrome 51.0.274.103

**Comment by elisei** [comment]
Olá @andersonkoester veja no log do magento, possivelmente é a tabela do checkout que não foi criada!

**Comment by andersonkoester** [comment]
@elisei, o erro apenas acontece no cenário acima. Utilizando outra versão do chrome ou até mesmo outro sistema operacional, não há replicação do erro

**Comment by elisei** [comment]
@andersonkoester  ao parece é um problema do navegador. 
Por isto versões recentes ou até anteriores executavam corretamente.
