### ISSUE TITLE
Imposto não calculado no Checkout

### ISSUE THREAD

**Issue by Gambozo** [elisei/moip-transparente-magento#60]
Em uma loja usando Magento 1.9.1, uso o módulo de frete "Easy Shipping Rules" para apresentar cotações através de faixa de CEP.
Por utilizar transportadoras e vender para todo o Brasil, é necessário utilizar a opção de regras para imposto no painel adm "Vendas/Impostos" para os estados RN, CE, MS, MT e DF. Porém, a regra somente verifica faixas de CEP no formato 00000000 (8 dígitos, sem hífen) e exige que estejam neste formato.
Ao entrar em processo de checkout no módulo MOIP, na tela anterior àquela de sucesso, onde escolhemos a forma de pagamento, somente o frete é exibido, não chamando o imposto e consequentemente deixando de coletar a taxa para o estado.
Percebi que o módulo do MOIP exige o formato 00000-000, tanto que ao corrigir o CEP do cliente pelo painel adm, ao logar e ir para checkout, é solicitada a correção do mesmo.
Há alguma forma de chamar o imposto mesmo com os formatos diferentes, ou é necessária normalização?
Desde já, agradecido pela atenção!

**Comment by elisei** [comment]
olá @Gambozo a regra do hifem, é por que é um padrão nacional, por isto a alteração deverá ser no módulo caso use esse aqui -> https://github.com/matheusgontijo/easy-shipping-rules/blob/882b04bfda0eb6495e56f3b138823ecd844d2709/app/code/community/MatheusGontijo/EasyShippingRules/Model/Shipping/Quote/Address.php#L39
basta alterar a linha de:    
$request->setDestPostcode(​str_replace(‘-‘,”,$this->getPostcode()));
para:
