### ISSUE TITLE
Status de Pedidos

### ISSUE THREAD

**Issue by Gambozo** [elisei/moip-transparente-magento#61]
A opção para definir o status de pedidos do módulo desapareceu?

Sem atualização:

![image](https://user-images.githubusercontent.com/22913826/43209316-b2ddab6a-9002-11e8-85d3-066d6c520b2b.png)

No módulo atualizado:

![image](https://user-images.githubusercontent.com/22913826/43209164-603632c4-9002-11e8-9551-fed2239a3a6c.png)

Onde encontro essas configurações atualmente? Eram extremamente úteis para converter compras por boleto.

**Comment by elisei** [comment]
@Gambozo então como pode notar de fato removemos. 
Atualmente status é definido com new. Há ações específicas para pedidos pendentes entre elas envio de email próprio, que você pode definir na sessão de emails de venda.

**Comment by elisei** [comment]
Olá @Gambozo 

Então vocẽ pode a qualquer momento trocar a label do status, alem disso tb recomendo instalar esse módulo https://github.com/iplaydu/BL_CustomGrid assim consegue facilmente associar a forma de pagamento diretamente no grid.
