### ISSUE TITLE
O widgets do parcelamento some depois de é aberto

### ISSUE THREAD

**Issue by luizgustavoagomes** [elisei/moip-transparente-magento#64]
Depois de clicar no parcelamento ele não fecha sozinho, e depois clicando nele ele desaparece, teria como deixar ele aberto sempre ?

**Comment by elisei** [comment]
@luizgustavoagomes 
Esse comportamento é devido a um conflito entre o boostrap e prototype é possível tratar habilitando o o uso do NoConflit em moip avançado isto injeta o tratamento desse conflito: https://github.com/elisei/moip-transparente-magento/blob/master/js/MOIP/core/jquery_noconflict.js#L5-L20
