### ISSUE TITLE
Trigger 'focus' no popover não funciona

### ISSUE THREAD

**Issue by Gambozo** [elisei/moip-transparente-magento#65]
Mediante solicitação de um cliente, transformei o widget de parcelamento na página do produto em um botão usando CSS. Ao tentar alterar a maneira que o popover() trabalha, percebi que usando o _trigger_ 'focus' para que qualquer clique na tela desative o popover, nem ao menos exibe o popover com as parcelas. O posicionamento no _placement_ para 'bottom' está perfeito, porém, se tentar utilizar o _trigger_ focus, mesmo combinado com outro, não exibe os parcelamentos.
Fiz alterações no arquivo **parcelas.phtml** no caminho: **app/design/frontend/base/default/template/MOIP/product/view**
O original está intacto, pois repliquei na estrutura do tema.
Usar o _trigger_ 'focus' seria interessante, pois há conteúdo abaixo do widget de parcelamento que é essencial para conclusão da compra, tal como opções personalizadas. Com o popover sobre eles, é necessário um clique exatamente no botão para desativá-lo e afeta a navegabilidade.
O Magento é 1.9.3.8, tema Porto v3.0.4 e o módulo está atualizado para última versão.
NoConflit jQuery está ativado.
No console não lista erros nem alertas.

**Comment by elisei** [comment]
@Gambozo 

Tente usar o trigger como hover, o comportamento é bem semelhante...
