### ISSUE TITLE
MOIP buga Fatura de pedido interno

### ISSUE THREAD

**Issue by davirs** [elisei/moip-transparente-magento#67]
Bom dia.
O módulo da MOIP impede que pedidos internos com pagamento padrão do magento sejam faturados

![image](https://user-images.githubusercontent.com/4355062/46469960-5e495780-c7ab-11e8-8472-acdaa690108e.png)

**Comment by elisei** [comment]
@davirs quando está faturando manualmente você deverá usar a opção de fatura off-line! na captura on-line é verificado se o pedido está ou não pago.

**Comment by elisei** [comment]
@davirs 
Sim todos testes feitos em nossa loja demo, por favor analise o log da sua aplicação ele pode revelar o real problema.

**Comment by davirs** [comment]
@elisei Não há nada errado nos logs nem na loja. Eu resolvi o problema dando rollback na vesão do checkout. Provavelmente incompatibilidade
