### ISSUE TITLE
Erro 404 com Carrinho persistente habilitado

### ISSUE THREAD

**Issue by phdiegues** [elisei/moip-transparente-magento#68]
Olá pessoal. Instalei o Modulo Moip Transparente e achei sensacional.

Após resolver alguns errinhos que aconteciam em minha loja um deles eu nao consigo resolver nem a porrete. rss  Seguinte:

Quando estou com o carrinho persistente habilitado, ao logar na conta e após a sessão expirar, quando vou ao carrinho e clico em "Fechar Pedido" Ele me retorna um erro 404 logo acima do campo para adicionar o e-mail no checkout (veja na imagem abaixo)

![1](https://user-images.githubusercontent.com/6341299/47097537-02012180-d208-11e8-9409-c393a372e767.jpg)

Lembrando que este erro só ocorre com o carrinho persistente habilitado.

Agradeço antecipadamente a todos que puderam ler na tentativa de ajudar.

Abraço a todos.

**Comment by elisei** [comment]
Olá @phdiegues tudo bem?

Acredito que o problema não esteja diretamente ligado ao persistência do carrinho e sim a configuração do fluxo de finalização nativo (+ detalhes aqui https://github.com/elisei/moip-transparente-magento/wiki/1---Como-Instalar#22-habilitar-checkout-onepage-e-perfil-de-acesso-ao-checkout) 

Ocorre que há um valor que fica oculto caso a opção "Cliente Precisa Ser Registrado p/ Finalizar Pedido" esteja definida como sim e por isto não consegue edita-la a menos que esse valor seja não!
 
Você poderá apenas mudar a opção "Cliente Precisa Ser Registrado p/ Finalizar Pedido" quando o valor  "Permitir Checkout como Visitante" é definido não quando isto acontece um novo campo irá aparecer, "Permitir Checkout como Visitante" você deverá defini-lo como sim, então salve, e depois ai poderá definir "Cliente Precisa Ser Registrado p/ Finalizar Pedido" como não e ai salvar novamente.
--

**Comment by phdiegues** [comment]
Resolvido!!!
Cara, muuuito obrigado pela ajuda. Você é fera!
