### ISSUE TITLE
Faturas repetidas

### ISSUE THREAD

**Issue by edigomes** [elisei/moip-transparente-magento#7]
Quando o cliente paga o magento cria 6 faturas repetidas para a mesma venda, alguém teve este problema? estou estudando o código para tentar resolver...

**Comment by elisei** [comment]
Olá @Edigomes,

Sua versão se encontra atualizada?

**Comment by edigomes** [comment]
Opa @elisei, tranquilo? Estou com a **master** instalada, percebi que os emails só duplicam em Produção, em Homologação funciona corretamente, é como se o retorno do pagamento viesse varias vezes, mas acho que não é isso, provavelmente a função `autorizaPagamento()` é executada varias vezes, no meu caso 5 vezes.

**Comment by elisei** [comment]
Você está usando a mesma conta sua homologação e em seu ambiente de produção?

**Comment by edigomes** [comment]
Não, produção/produção, homologação/homologação, tudo certinho.

**Comment by elisei** [comment]
Okay, 

Se o modulo está atualizado você deve ter mais de uma notificação configurada mesmo. Para analisar isto é necessário que envie o oauth da produção (no email e não por aqui) ou pode fazer sozinho, dando um get em:
https://api.moip.com.br/v2/preferences/notifications/
Authorization: OAuth SEUOAUTH

**Comment by elisei** [comment]
Depois o mesmo antes de uma olhada se está igual:

https://github.com/elisei/moip-transparente-magento/blob/master/app/code/local/MOIP/Transparente/controllers/StandardController.php#L89

**Comment by edigomes** [comment]
http://pastebin.com/BfJ7e6ZE
Realmente, varias notificações configuradas, acho que como fiz varias instalações até encontrar a versão mais estável ele fez a cfg de retorno varias vezes, e para remover? Tem na API ou vou ter que tratar no código mesmo?

**Comment by elisei** [comment]
@edigomes 
Só dar um del:

**Comment by elisei** [comment]
@edigomes só um detalhe se o StandarController tiver atualizado ele pegaria as demais requisições confira se o arquivo está também atualizado...

**Comment by edigomes** [comment]
@elisei O **StandarController** atual está igual a do master, provavelmente as versões configuradas antes por mim estavam sem as requisições, 

Peguei a desatualizada direto pelo Magento Connect: [https://www.magentocommerce.com/magento-connect/moip-transparente-oficial.html](url), seria uma boa atualizar lá, visto que a maioria tenta primeiro por lá!

Vou dar o DELETE pra ver se fica tudo OK!

**Comment by elisei** [comment]
@edigomes valeu abraços!
