### ISSUE TITLE
Esqueceu senha direto no checkout não funciona

### ISSUE THREAD

**Issue by italo007** [elisei/moip-transparente-magento#71]

**Comment by italo007** [comment]
fazendo solicitação direto pelo checkout para trocar senha , não funciona , email do magento ok, troca de senha pelo minha conta direto do magento funciona , porem pelo checkout moip não envia email de troca de senha.

**Comment by elisei** [comment]
@italo007 por favor verifique suas configurações de enveio, ou encaminhe log que possa descrever melhor o erro.
