### ISSUE TITLE
Pedido Cancelados sem Informações

### ISSUE THREAD

**Issue by Gambozo** [elisei/moip-transparente-magento#73]
Olá!
Utilizava, em uma das lojas que mantenho, uma versão do módulo que não havia a id MPA explicitamente exibida em "MOIP Avançado" e foi solicitada atualização. Com a atualização, foi refeita a autorização do módulo e as informações do módulo estavam OK.
Verificando os pedidos, vários ficaram com a mensagem "Não foi possível recuperar a informação do pagamento." no campo "Informações de pagamento".
Até aí tudo bem, pois eram poucos pedidos que precisariam ser confirmados dentro do MOIP pelo financeiro.
Porém alguns mais recentes, que precisaram ser cancelados, estão abrindo vazios.
![image](https://user-images.githubusercontent.com/22913826/52146952-64adea00-264c-11e9-93ef-aa4aad87b67a.png)

Olhando o "system.log", tenho duas saídas:
2019-02-01T19:42:23+00:00 ERR (3): Notice: Undefined index: moip_transf_href  in /public_html/app/code/local/MOIP/Transparente/Block/Info/Tef.php on line 13
2019-02-01T19:42:32+00:00 ERR (3): Notice: Undefined index: line_code  in /public_html/app/code/local/MOIP/Transparente/Block/Info/Boleto.php on line 14

Poderia me auxiliar na solução deste problema?
Obrigado!

**Comment by elisei** [comment]
Caso não tenham resolvido por favor reabra o ticket.
