### ISSUE TITLE
Cannot use isset() on the result of an expression

### ISSUE THREAD

**Issue by warleyelias** [elisei/moip-transparente-magento#75]
Não se pode utilizar isset no resultado de uma expressão.

https://github.com/elisei/moip-transparente-magento/blob/master/app/code/local/MOIP/Transparente/Model/Api.php#L329

Array ( [type] => 64 [message] => Cannot use isset() on the result of an expression (you can use "null !== expression" instead) [file] => app/code/local/MOIP/Transparente/Model/Api.php [line] => 329 )

**Comment by tiagoexe** [comment]
Olá [warleyelias](/warleyelias), estou tendo esse mesmo problema. sabe como posso resolver?

abs

**Comment by warleyelias** [comment]
> Olá [warleyelias](/warleyelias), estou tendo esse mesmo problema. sabe como posso resolver?
> 
> abs

Nesse caso a solução depende do próprio moderadores do repositório, que nesse caso é o Elisei, porém uma solução rápida é fazer o fork desse projeto e fazer a correção onde você mesmo seja o dono do repositório.
Outra possível solução é baixar o pacote com esse problema e fazer a correção, no meu caso isso funcionou pois mesmo baixando a versão com erro eu tenho meu próprio controle de versão para todo o código.
E no mais é esperar a solução por parte dos moderado do repositório.

Outra coisa @tiagoexe é que existe outro erro que está no ticket que eu também criei.
https://github.com/elisei/moip-transparente-magento/issues/74

**Comment by elisei** [comment]
@warleyelias @tiagoexe 
Soltei um update por favor verifique!
