### ISSUE TITLE
Checkout não processa Boleto ou Débito

### ISSUE THREAD

**Issue by claudiobiato** [elisei/moip-transparente-magento#76]
Olá Elisei, 

Meu magento 1.9.0.1
Instalei e configurei o módulo, ok.
Para recebimentos com cartão de crédito, ok, testado e recebido pela wirecard.
Mas o módulo não seleciona o Boleto Bancário e o Débito em conta.
Retirei as prioridades de exibição no módulo e não funcionou.

Tenho aqui um log do magento:

2019-03-06T02:48:37+00:00 ERR (3): Notice: Undefined variable: amount  in app/code/local/MOIP/Transparente/Model/Sales/Quote/Address/Total/Fee.php on line 45

Troquei o arquivo Fee.php por um antigo que instalei em 2018 e o erro saiu do log.

Mas mesmo assim ainda não consigo selecionar a opção de pagamento Boleto ou Débito.

Poderia por gentileza verificar este erro, enviei um e-mail para vc.

Agradeço.

**Comment by elisei** [comment]
@claudiobiato 

Caso ainda tenha dificuldades por favor reabra o issues.
