### ISSUE TITLE
Não funciona após instalação

### ISSUE THREAD

**Issue by apzeiro** [elisei/moip-transparente-magento#79]
Fiz a instalação rigorosamente conforme manual, mas ao testar pela primeira vez dá um erro e o site trava:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento.moip_transparentev2' doesn't exist, query was: SELECT COUNT(*) FROM `moip_transparentev2` AS `main_table` WHERE (`customer_id` = '1') AND (`moip_ambiente` = 'producao') AND (`moip_card_id` != 'NULL') GROUP BY `moip_card_id`

**Comment by elisei** [comment]
Olá @apzeiro 

O log está informando que não achou no seu banco a tabela, tente forçar a criação dele.
