### ISSUE TITLE
O passo 2 não está funcionado.

### ISSUE THREAD

**Issue by designdw** [elisei/moip-transparente-magento#8]
O passo 2 não funciona, quando clico em "Autorizar Moip", faço o login na minha conta do Moip e autorizo, carrega uma página com o seguinte: 

Forbidden

You don't have permission to access /magento/redirect/ on this server.

Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by elisei** [comment]
@designdw 

Você está usando um dominio temporário, cuja a sessão não pode ser atingida, por favor via suporte.o2ti.com encaminhe o a url completa em está caindo na página de erro.
