### ISSUE TITLE
Frete não carrega na página de checkout

### ISSUE THREAD

**Issue by mpgmateus** [elisei/moip-transparente-magento#80]
Olá, boa tarde!

Estou tentando finalizar a compra em minha loja e não estou conseguindo devido ao não carregamento do frete. Obs: estou utilizando o módulo do correios do Pedro Teixeira.

Vamos lá:

<a href="https://ibb.co/hdgSdc9"><img src="https://i.ibb.co/2MFTMSh/Captura-de-Tela-2019-05-22-a-s-13-27-48.png" alt="Captura-de-Tela-2019-05-22-a-s-13-27-48" border="0"></a><br />

<a href="https://ibb.co/ZXxJCny"><img src="https://i.ibb.co/JtHdPfX/Captura-de-Tela-2019-05-22-a-s-13-28-03.png" alt="Captura-de-Tela-2019-05-22-a-s-13-28-03" border="0"></a><br />

Como podemos ver, fica essa barrinha verde e nada de aparecer as opções do frete.

Assim, dei um inspect e fui no console e detectei esses erros 403.
Acredito que não esteja carregando por conta deles.

Aah e antes que eu esqueça... o link da loja é https://www.ifitfitsonline.com

Qual seria a melhor saída para esse caso?

Espero que possam me ajudar!

Att,
Mateus

**Comment by elisei** [comment]
Olá @mpgmateus 

Isso é uma sessão expirada, procure analisar as configurações de sessão do seu magento.
