### ISSUE TITLE
Erro cartao de credito

### ISSUE THREAD

**Issue by fredioppe** [elisei/moip-transparente-magento#82]
bom dia, estou tendo esses retorno de erro...alguma ideia?

{"errors":[
{"code":"PAY-631","path":"","description":"O código de segurança do cartão não foi informado"},
{"code":"PAY-622","path":"","description":"O ano de expiração do cartão não foi informado"},
{"code":"PAY-623","path":"","description":"O ano de expiração do cartão de crédito deve ser numérico"},
{"code":"PAY-619","path":"","description":"O mês de expiração do cartão de crédito não foi informado"},
{"code":"PAY-620","path":"","description":"O mês de expiração do cartão de crédito deve ser numérico"}]}

**Comment by elisei** [comment]
Olá @fredioppe é necessário configurar a autorização do app, você já fez isso?

**Comment by fredioppe** [comment]
@elisei sim já está autorizado

![image](https://user-images.githubusercontent.com/51825653/59513048-64dab380-8e90-11e9-8812-ffabbf92f804.png)

**Comment by elisei** [comment]
@fredioppe, 

Pode ser algum erro de js que impede a geração da hash do cartão, verifique os artigos de nossa Wiki para orientações sobre o tema.
