### ISSUE TITLE
Atualização para pagamento a vista no cartão não funciona

### ISSUE THREAD

**Issue by iluminifast** [elisei/moip-transparente-magento#84]
Bom dia, fiz a atualização do modulo paga a opção de pagamento via cartão de credito em 1x sem juros, porem não está funcionando. Fui em Sistemas/Configurações/Vendas/Formas de Pagamento/Moip Transparente Cartão de Credito/ Aplicar desconto compra avista/ e apliquei -5.00 limpei cache e tudo mais e nada, na finalização continua igual. Poderia me ajudar por favor?

Att, André

**Comment by elisei** [comment]
Oi @iluminifast, 

Verifique se seu módulo está atualizado, ou mesmo se há algum conflito com outros módulos em seu magento.

**Comment by iluminifast** [comment]
Verifiquei, está tudo certo, sem conflito, tem alguma ideia mais do que possa ser?

**Comment by elisei** [comment]
Não, em nossa loja demo, com essa exata versão está funcionando. 
https://wirecard2.loja.ninja/

**Comment by phdiegues** [comment]
Oi Bruno, tudo bem? como faço pra deixar o checkout em 3 passos conforme está na sua loja demo?
Abraços, parabéns e obrigado!
