### ISSUE TITLE
Erro no checkout com Kaspersky

### ISSUE THREAD

**Issue by leandromendonca** [elisei/moip-transparente-magento#85]
Olá Bruno.

Há algum tempo temos recebido ligações de clientes dizendo que não conseguem colocar os dados do cartão na tela do checkout. Logo após a escolha da opção de frete, o bloco dos pagamentos fica com uma barra de "loading" e não avança.

Descobrimos que a situação acontece com usuários do antivírus Kaspersky, que bloqueia o script /onestepcheckout/index/updatepaymenttype. Veja a tela anexa:

![erro-kaspersky](https://user-images.githubusercontent.com/29495597/62396416-8e879100-b549-11e9-9367-0882e96cb32b.jpg)

De fato, se o cliente desligar momentaneamente o antivirus, ou colocar o scritpt na lista de exceções, o checkout é completado normalmente.

Você já viu este problema? Tem ideia do que fazer para corrigir?

Desde já agradeço.

Leandro.

**Comment by elisei** [comment]
@leandromendonca 

Recomendo que realize o contato direto com Kaspersky para maiores informações.
