### ISSUE TITLE
Como substituir o cadastro padrão do magento pelo da moip?

### ISSUE THREAD

**Issue by carlosjaquetto** [elisei/moip-transparente-magento#87]
O cadastro da moip só entra quando já possui algum item no carrinho e você tenta finalizar a compra, teria como substituir isso para deixar ele como padrão se a pessoa quiser se cadastrar antes de tentar realizar uma compra ?

**Comment by elisei** [comment]
Olá Carlos, 

O cadastro é sempre do Magento, não há redirecionamentos a outros sites em nosso módulo, mas se você está tentando direcionar clientes sem produtos no carrinho para o cadastro de finalização de pedido você não irá conseguir uma vez que o carrinho é destinado a compradores.
