### ISSUE TITLE
SwitchMethod() duplo clique

### ISSUE THREAD

**Issue by guittavares** [elisei/moip-transparente-magento#88]
Boa tarde, estou tento problemas na hora de escolher a forma de pagamento.
Preciso dar duplo clique na opção para carregar o método.
Gostaria que o clique fosse único.

Poderia me ajudar por favor?

**Comment by elisei** [comment]
Olá @guittavares, tudo bem?

Posso sim, mas você pode me passar o seu site por favor?

**Comment by guittavares** [comment]
Muito obrigado pelo retorno
maximacor.com.br

**Comment by guittavares** [comment]
Muito obrigado pelo retorno
http://maximacor.com.br

**Comment by elisei** [comment]
Olá @guittavares 

Você precisa corrigir os erros de js que o site apresenta, os do checkout você pode seguir a nossa wiki:
https://github.com/elisei/moip-transparente-magento/wiki/3-Configurar-Checkout-Moip-Carrinho#2-conflito-de-js

Além disso o tempo de resposta do site está extramente alto, 1 minuto e 30 segundos foi o tempo de resposta para a sua página de produto, o checkout também está recebendo alto impacto, 30 segundos de load o que pode dar essa percepção de ter que clicar 2 vezes sobre a forma de pagamento.

**Comment by guittavares** [comment]
Eliminei os erros e o tempo de resposta já diminuiu para 5 segundos.
Mesmo assim continua igual.

**Comment by guittavares** [comment]
Olá bom dia, ainda não consegui resolver esta questão, poderia me dar uma ajuda?

**Comment by elisei** [comment]
Olá @guittavares ,

O problema ainda é js você está com 3 bibliotecas da jQuery rodando no checkout... Remova todas as demais (conforme a orientação https://github.com/elisei/moip-transparente-magento/wiki/3-Configurar-Checkout-Moip-Carrinho#2-conflito-de-js)
