### ISSUE TITLE
Erro ao realizar pagamento - Boleto

### ISSUE THREAD

**Issue by silvergama** [elisei/moip-transparente-magento#91]
Olá, estou com magento na versão 1.8 e começou a dar problema no boleto.

Quando clico em finalizar pedido ele redireciona tudo certinho, mas quando clico em `visualize o boleto aqui` ou uso o link da essa mensagem abaixo

![image](https://user-images.githubusercontent.com/14098038/67821853-40791f80-fa9d-11e9-9245-96b3377c02d2.png)

já verifiquei todos os dados e está tudo certo, mas mesmo assim da esse erro.

Pode dar uma ajuda?

Valew

**Comment by elisei** [comment]
Oi @silvergama 

Você precisa atualizar a versão do módulo, o que usa consome a api 1.0 da wirecard, essa nova versão é na api 2.0 além de novos recursos é muito mais estável.

**Comment by silvergama** [comment]
Fala @elisei, blz?
Eu fiquei no receio de atualizar e tal, como a loja é muito antiga bateu aquele medo hahahah

![WhatsApp Image 2019-10-29 at 22 21 42](https://user-images.githubusercontent.com/14098038/67868508-d7c88c00-fb0a-11e9-9730-f0ad7b8be27f.jpeg)

Acha que posso atualizar para 1.3.11 direto?

Se atualizar para 2.x vai dar ruim né?

**Comment by elisei** [comment]
Olá @silvergama 

Não faça pelo connect, ele deixou de receber updates, você deve realizar com a versão aqui do git, mas claro, faça um backup antes, e se possível faça primeiro em um ambiente de teste.
