### ISSUE TITLE
Problema com Widget

### ISSUE THREAD

**Issue by iluminifast** [elisei/moip-transparente-magento#93]
Bom dia, o modulo está funcionando perfeitamente, porem no widget que exibi as formas de pagamento na pagina do produto ao clicar ele abre corretamente, e ao clicar novamente para fechar a escrita com o valor das parcelas some e só aparece novamente ao carregar a pagina de novo. O console não apresenta nenhum erro. Saberia o que pode esta causando isso? 
Att,
André

**Comment by elisei** [comment]
Olá,

É um conflito com prototype.
