### ISSUE TITLE
Modulo nao mostra mensagens de campos nao preenchidos para usuarios

### ISSUE THREAD

**Issue by phdiegues** [elisei/moip-transparente-magento#94]
Boa noite a todos. Tenho uma loja (www.bigartesanato.com.br) e notei que o modulo não mostra a mensagem ("Selecione o número de parcelas") quando o usuário não escolhe. Ao clicar em "Finalizar pedido" Nada acontece. Consigo ver a mensagem apenas no exeption.log

Alguem poderia me dar uma luz?

Antecipadamente agradeço a todos.
Abração!

**Comment by phdiegues** [comment]
Bom dia pessoal, ainda não consegui resolver este errinho...

**Comment by elisei** [comment]
Olá @phdiegues  por favor forneça detalhe de como reproduzir o erro, por aqui não fomos capazes de produzi-lo.
