### ISSUE TITLE
Modulo não está alterado o status dos pedidos

### ISSUE THREAD

**Issue by CarlosFatigate** [elisei/moip-transparente-magento#95]
Os pedidos não estão tendo o seu status atualizado, no magento continuam como pendente mas no moip eles estão como pagos.
 Utilizo o mangento 1.9

**Comment by elisei** [comment]
@CarlosFatigate 
Por favor analise o tópico da wiki -> https://github.com/elisei/moip-transparente-magento/wiki/Webhooks
