### ISSUE TITLE
Configuração de produto para assinatura

### ISSUE THREAD

**Issue by ricardomoreti** [elisei/moip-transparente-magento#97]
Boa tarde, tudo bem?

Gostaria de saber como funciona a parte de assinaturas do Moip com o Magento 1.9.x, vi nos detalhes do módulo que tem e gostaria de saber como configurar.

No meu caso é uma loja de livros e o pessoal tem a opção de compra avulsa e também efetuar a assinatura, trimestral, semestral e anual.

No aguardo, muito obrigado desde já.

**Comment by elisei** [comment]
Oi @ricardomoreti tudo bom e você?

Não há nenhuma configuração "especial" para usar a recorrência, basta apenas ativar o método de pagamento e quando for um pagamento do tipo corrente e estará disponível no checkout!
