### ISSUE TITLE
Erro 403 após cadastro no Checkout

### ISSUE THREAD

**Issue by Gambozo** [elisei/moip-transparente-magento#98]
Bom dia, Elisei!
Atualizei o módulo de 2 lojas, porém estão acontecendo estes erros ao completar o cadastro e ir para a tela de pagamento, em ambas.
![image](https://user-images.githubusercontent.com/22913826/76980392-e2e45300-6917-11ea-944b-a96e880fe8b9.png)
Tal erro só acontece quando o cliente faz a compra sem realizar cadastro previamente, deixando para se cadastrar durante o checkout.
Algumas vezes o cliente é redirecionado para a home, com carrinho vazio. No sistema o cadastro foi realizado normalmente. Ao que parece, o cliente é "kickado" da sessão ao finalizar seu cadastro.
Se o cliente faz seu cadastro no form padrão do Magento ou realiza login antes de ir para a tela de checkout, é possível finalizar a compra sem problemas.
Verifiquei os dados de sessão e parecem OK. Observe:
![image](https://user-images.githubusercontent.com/22913826/76981534-7cf8cb00-6919-11ea-895c-5b99d11a8a35.png)

As sessões estavam sendo salvas no banco de dados. Mudei para sessões em arquivos e mesmo assim o problema continua. 
Rodei as permissões de arquivos novamente... o erro persiste.
Consegue me ajudar?

**Comment by elisei** [comment]
Olá @Gambozo 

Dê uma olhada nessa dica aqui:
https://magento.stackexchange.com/questions/64063/frontend-login-not-working-in-chrome-with-https-enabled-1-9/200609#200609

**Comment by Gambozo** [comment]
Perfeito! Obrigado!
