### ISSUE TITLE
Erro mascaras de CPF, CEP e Telefone

### ISSUE THREAD

**Issue by awakebrasil** [elisei/moip-transparente-magento#99]
Olá, primeiro ótimo modulo. 

Vamos lá, atualizamos o modulo e vimos que as mascaras não funcionam na parte de cadastro em CEP, Telefone, CPF, tudo funciona OK, mas os dados estão vindo sem das devidas pontuações. 

Saberia me informar como resolver, obrigado.

**Comment by elisei** [comment]
Olá @awakebrasil 

Por favor analise o tópico de erros de js da Wiki:
https://github.com/elisei/moip-transparente-magento/wiki/3-Configurar-Checkout-Moip-Carrinho#2-conflito-de-js
